# Generated by Django 4.2.7 on 2023-12-01 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_code', models.CharField(blank=True, max_length=6, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('current_digital_skills', models.TextField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(upload_to='profile')),
                ('adminsion', models.CharField(choices=[('on progrss', 'on progrss'), ('approved', 'approved')], default='on progrss', max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
