# Generated by Django 4.2.7 on 2023-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_verified',
            field=models.BooleanField(default=False),
        ),
    ]
