# Generated by Django 4.2.7 on 2023-12-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0005_remove_profile_username_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adminsion',
            new_name='admission',
        ),
    ]
