# Generated by Django 4.2.7 on 2023-12-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0006_rename_adminsion_profile_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
