# Generated by Django 4.2.7 on 2023-12-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0007_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission',
            field=models.CharField(choices=[('on progress', 'on progress'), ('approved', 'approved')], default='on progress', max_length=200),
        ),
    ]
