# Generated by Django 4.2.7 on 2023-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0009_alter_profile_current_digital_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_digital_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
