# Generated by Django 4.2.7 on 2023-12-01 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singup', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Createcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(upload_to='task')),
                ('duration', models.DateField(auto_now_add=True)),
                ('whatsapp_group', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('Reason', models.TextField()),
                ('work', models.CharField(blank=True, max_length=200, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycourse', to='courses.createcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.createcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.TextField(blank=True, max_length=500, null=True)),
                ('uplaod_profile', models.ImageField(upload_to='profile')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.createcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
